### ISSUE TITLE
Unset grpcPath doesn't have correct behavior

### ISSUE THREAD

**Issue by aughey** [5argon/protobuf-unity#16]
Line 117 in Editor\ProtobufUnityCompiler\ProtobufUnityCompiler.cs I believe should have && instead of ||.  

I'm not using (current) grpc, so I don't have that value set in the prefs.  So that string is empty.  But written with || this statement evaluates to true.

**Comment by gardenofnumbers** [comment]
Seconded. When the string is empty, it still looks for grpc and fails to compile

Editing this fixed that behavior

**Comment by 5argon** [comment]
Oh no, I have not checked this for long time and it seems a PR #13 is already doing that fix. I have merged it now.
