### ISSUE TITLE
Error when Path to protoc contain space character

### ISSUE THREAD

**Issue by Guxin233** [5argon/protobuf-unity#2]
Path to protoc nonsuport contain space character. For example if my project folder path like D:/Unity Leaning, when I click Force Compilation , it console error cannot find folder D:/Unity

**Comment by 5argon** [comment]
Ah shoot, I just realized my game contains no space in paths at all out of a habit of naming folders in pascal case. I will have a look at it.

Should be around sending commands to `System.Diagnostics.Process` (Bottom of `ProtobufUnityCompiler.cs`) where we can escape with quotes or something just in case you want to fix it yourself.

**Comment by Guxin233** [comment]
OK, I find it is "excPath" filed , and str.Replace(" ","") to take out the space.
