### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by loeffel-io** [5argon/protobuf-unity#20]
Hey, 

have some problems after added the package via the package manager (unity 2020.3.11f1) `Library\PackageCache\com.e7.protobuf-unity@2956da0dde\Runtime\ProtoBinaryManager.cs(88,19): error CS0246: The type or namespace name 'IMessage<>' could not be found (are you missing a using directive or an assembly reference?)` (one of the error messages)

- Already cleared the PackageCache
- Protoc is available

**Comment by 5argon** [comment]
Hi, that type came from Google's protobuf DLL. The generated code will all
have dependencies to that.

You need to search for that in the Nuget. After a certain version (where it
says it supports .NET Standard 2.0 IIRC?) it will start using some other
DLL that Unity does not have as well, I recommends sticking with the
version that works with only 1 Protobuf DLL added.
