### ISSUE TITLE
Can't find Google.protobuf

### ISSUE THREAD

**Issue by akoolenbourke** [5argon/protobuf-unity#7]
Hi there. I assume I'm doing something obviously wrong but I installed your code and unity is complaining with this error

The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)

ProtoBinaryManager is trying to using using Google.Protobuf;

Is there something else I need to do?

**Comment by 5argon** [comment]
You have to add the dll of Protobuf to Unity project. Your generated
classes will need it too.

2019年8月16日(金) 12:51 Aaron Koolen-Bourke <notifications@github.com>:

**Comment by akoolenbourke** [comment]
Thanks!

**Comment by jswigart** [comment]
Sorry to revive this but it seems better than starting a new issue. I added this project to my unity project via a package manager git url, and I have the Google.Protobuf.dll in my project, and my unity project appears to reference it fine(no compiler errors), but it appears that this project, when linked as a package, doesn't reference that plugin in the same way.

For example:
Library\PackageCache\com.e7.protobuf-unity@54efa9d8767d0c06b31d984b4c200c0465e0e8a7\Runtime\ProtoBinaryManager.cs(1,7): error CS0246: The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)

Is there a more appropriate way to set up the reference to this project when it's imported as a unity package?

**Comment by jswigart** [comment]
I see the reference to Google.Protobuf.dll in the assembly definition E7.ProtobufUnity.asmdef. Is there a special place this assembly needs to be located for this package to find it?

**Comment by karoletrych** [comment]
@jswigart  it should be placed in the Assets folder. Use version 3.6.0 instead of the newest too cause newest requires System.Math.
