### ISSUE TITLE
Multiple references to Any, Timestamp etc

### ISSUE THREAD

**Issue by akoolenbourke** [5argon/protobuf-unity#8]
Hi there. I was trying to understand the docs regarding the importable google supplied proto classes like Any, Timestamp etc but I wasn't sure how to ensure they are importable into my own .proto files. If I place them anywhere in my Unity project, your library will compile them into classes but then I get warnings about duplicate references between the google dll (I assume it's that) and those files.

What is the recommended way to use the google .proto files with your library?

Thanks
Aaron

**Comment by 5argon** [comment]
Hi, I took a screenshot from my proto definition. This is how you use it :

<img width="840" alt="Screenshot 2019-08-21 16 42 27" src="https://user-images.githubusercontent.com/5653276/63421559-f9363900-c432-11e9-8868-0e5bf90b4170.png">

So the class is already there in the Protobuf.dll, and in `using Google.Protobuf` (try typing `Google.Protobuf.WellknownTypes.` and you will find them in the intellisense.) If you copy it again to your game then it's a duplicate declaration. So what's left is just letting Protobuf generating the C# class. The generated property declaration will look like this :

<img width="716" alt="Screenshot 2019-08-21 16 43 59" src="https://user-images.githubusercontent.com/5653276/63421592-0f43f980-c433-11e9-887c-456907114a07.png">

**Comment by akoolenbourke** [comment]
Thanks for the reply but the compiler can't find timestamp.proto. 

Protobuf Unity : google/protobuf/timestamp.proto: File not found.

I use **import "google/protobuf/timestamp.proto";**

Intellisense in my.proto finds google.protobuf.timestamp as I type but then it seems to find both capitalised and non capitalised versions of Timestamp. Intellisense in c# code finds it, but it's a compile error even after using Google.Protobuf;


You mentioned 'Protobuf.dll' I assume you meant Google.Protobuf.dll? I assume I need some special build of this. There is no redistributable anywhere. I built it on Windows but maybe that didn't include the wellknowntypes

**Comment by akoolenbourke** [comment]
OK, I just rebuilt on mac and confirmed with ilspy that the WellKnownTypes were there in the dll. However the import still says it can't find the timestamp.proto file. Am I actually meant to put those files somewhere? Does protoc know to actually grab the proto imports from an actual dll??

**Comment by akoolenbourke** [comment]
And to follow up, in the end I had to find the wellknown types proto files and copy them to /usr/local/include
